// <auto-generated />
using System;
using Finance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finance.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20250608175904_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Finance.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Salário",
                            Type = 0,
                            Value = 3000m
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 6, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Mercado",
                            Type = 1,
                            Value = 250m
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Conta de luz",
                            Type = 1,
                            Value = 120m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
